# Generated by Django 4.0.2 on 2022-02-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('l', 'linux'), ('w', 'windows'), ('m', 'mac'), ('u', 'unix'), ('p', 'python')], max_length=20)),
                ('propmt', models.TextField(blank=True)),
                ('num_options', models.IntegerField()),
                ('option1', models.TextField(blank=True)),
                ('option2', models.TextField(blank=True)),
                ('option3', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
