# Generated by Django 4.0.2 on 2022-02-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='propmt',
            new_name='prompt',
        ),
    ]
